#!/usr/bin/env bash
# installing nginx

sudo apt-get install -y nginx
echo "Hello World!" | tee /usr/share/nginx/html/index.html > /dev/null
echo "Hello World!" | tee /var/www/html/index.html > /dev/null
sudo service nginx restart