#!/usr/bin/env bash
# installing nginx

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx start
sudo rm index.html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
