#!/usr/bin/env bash
# shellcheck disable=SC2154
# configures a brand new Ubuntu machine

sudo apt-get -y update
sudo apt-get -y install nginx
NEW_STRING="\\\tadd_header X-Served-By $HOSTNAME;\n"
sudo sed -i "37i $NEW_STRING" /etc/nginx/sites-available/default
sudo service nginx restart
